# Generated by Django 5.0.6 on 2024-07-19 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Realtionship', models.CharField(max_length=50)),
                ('Phone_no', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
    ]
